name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      # We build in Debug here so the script is exactly where the next step expects it
      run: dotnet build --configuration Debug -p:NoWarn=CS8618

    - name: Install Playwright Browsers
      # Using the absolute pathing based on your repository structure
      run: |
        pwsh ./E2EShoppingAutomation/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Playwright tests
      run: |
        dotnet test E2EShoppingAutomation/E2EShoppingAutomation.csproj --configuration Debug --no-build --settings E2EShoppingAutomation/playwright.runsettings

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots
        path: E2EShoppingAutomation/Screenshots/
        retention-days: 30